/**
 * What this package is allowed to ship, and — since M5a — what it is *required* to ship.
 *
 * At M3 and M4 the rule was absolute: **zero art assets in the build**, because M4 was the go/no-go
 * and *"Roughly 70% of why the reference image looks the way it does is renderer, lighting, fog and
 * grade — not meshes… If it reads as grey cylinders under a blue filter, stop and reconsider before
 * spending a single hour on assets."* A single texture sneaking in would have been a thumb on that
 * scale.
 *
 * **The owner has given the GO**, so M5a spends the hour. The rule does not go away, it narrows to a
 * shape, and the shape is §5's delivery note: art lives under `public/models/`, is fetched at run time
 * from a stable path, is never a Vite bundler import, and is **generated by
 * `packages/worldgen/src/treegen.ts`** rather than downloaded. So this file now asserts four things:
 *
 * 1. The only art in the package is under `public/models/trees/`, and every file there is either a
 *    `.glb` the manifest lists, the manifest, or the generated attribution note. Nothing else — no
 *    stray texture, no half-migrated Quaternius kit, and above all nothing under `src/`.
 * 2. **The manifest and `prototypes.ts` agree exactly.** That is the other half of the bounded-pool
 *    contract: `TREE_VARIANTS` x `TREE_PARTS` x `TREE_LODS` is a closed set enumerated at module load,
 *    and a baker that produced a ninth variant, or dropped the eighth, would either grow a tree
 *    nothing can draw or size the pool for one that does not exist.
 * 3. **The size budget.** M5a's brief asks for well under 5 MB and reports the real number; §7's
 *    frame-time trigger is the reason to keep it there rather than to let a hero asset in.
 * 4. Still one composer stack. §3's warning is unchanged and the rule is narrowed rather than dropped:
 *    `three/examples/jsm/loaders/GLTFLoader.js` is exactly the sort of thing the examples folder is
 *    *for* and has nothing to do with the composer; `three/examples/jsm/postprocessing` is the thing
 *    that must never appear beside pmndrs'.
 */

import assert from 'node:assert/strict';
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, extname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it } from 'node:test';

import { TREE_LODS, TREE_PARTS, TREE_VARIANTS, variantsFrom } from './prototypes.ts';
import { TREE_MANIFEST_VERSION, type TreeManifest } from './trees.ts';

const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TREES_DIR = join(PACKAGE_ROOT, 'public', 'models', 'trees');

/** Anything a renderer could draw, load or play. */
const ART = new Set([
  '.png',
  '.jpg',
  '.jpeg',
  '.webp',
  '.gif',
  '.bmp',
  '.tga',
  '.svg',
  '.glb',
  '.gltf',
  '.fbx',
  '.obj',
  '.dae',
  '.ktx2',
  '.basis',
  '.dds',
  '.hdr',
  '.exr',
  '.mp3',
  '.ogg',
  '.wav',
]);

/**
 * The whole tree set's budget, in bytes.
 *
 * Five megabytes is the brief's ceiling and the bake comes in at about a sixth of it, uncompressed —
 * no Draco, no meshopt, no KTX2, because §5 names `@gltf-transform/cli` for those and M5a is allowed
 * exactly one new dependency. The headroom is deliberate: it is what a second biome's kit is meant to
 * fit into, not what this one is meant to grow into.
 */
const TREE_SET_BUDGET = 5 * 1024 * 1024;

/** One level of detail's own ceiling. A hero asset would clear this on its own and must not arrive. */
const TREE_FILE_BUDGET = 256 * 1024;

function walk(dir: string, found: string[]): void {
  for (const entry of readdirSync(dir)) {
    // Installed dependencies are full of art; the question is what *this package* ships.
    if (entry === 'node_modules' || entry === 'dist' || entry === '.vite') continue;
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) {
      walk(path, found);
      continue;
    }
    if (ART.has(extname(entry).toLowerCase())) found.push(path);
  }
}

function walkSource(dir: string, found: string[]): void {
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) {
      walkSource(path, found);
      continue;
    }
    if (entry.endsWith('.ts')) found.push(path);
  }
}

describe('what the build is allowed to carry', () => {
  it('keeps every asset under public/models and none anywhere else', () => {
    const found: string[] = [];
    walk(PACKAGE_ROOT, found);
    const stray = found
      .map((path) => relative(PACKAGE_ROOT, path).replace(/\\/g, '/'))
      .filter((path) => !path.startsWith('public/models/'));
    assert.deepEqual(stray, [], `art outside public/models:\n${stray.join('\n')}`);
    // And nothing under `src/` at all: the renderer imports no asset, it fetches them.
    const inSource = found.filter((path) => path.includes(`${join('client3d', 'src')}`));
    assert.deepEqual(inSource, []);
  });

  it('depends on three, on the one composer stack, and on nothing else that draws', () => {
    const manifest = JSON.parse(readFileSync(join(PACKAGE_ROOT, 'package.json'), 'utf8')) as {
      dependencies: Record<string, string>;
      devDependencies: Record<string, string>;
    };
    // M5a's one new dependency is `@dgreenheck/ez-tree` and it is **worldgen's**, not this package's:
    // trees are build artefacts, so the generator never ships to a browser.
    assert.deepEqual(Object.keys(manifest.dependencies).sort(), ['@mygame/shared', 'postprocessing', 'three']);
    // Pinned exact, all three: `@types/three` is DefinitelyTyped and lags releases, and
    // `postprocessing` peers `three >=0.168.0 <0.186.0` — one minor of headroom from this pin, which
    // §3 warns *will* periodically brake upgrades and risk 5 budgets a maintenance day for.
    assert.equal(manifest.dependencies['three'], '0.185.1');
    assert.equal(manifest.dependencies['postprocessing'], '6.39.4');
    assert.equal(manifest.devDependencies['@types/three'], '0.185.1');
    // M7's and click-to-move's dependencies must not have wandered in early.
    for (const early of ['troika-three-text', 'three-mesh-bvh']) {
      assert.ok(!(early in manifest.dependencies), `${early} is not M5a's`);
      assert.ok(!(early in manifest.devDependencies), `${early} is not M5a's`);
    }
  });

  it('imports one composer stack and never three/examples postprocessing', () => {
    // §3, quoted where it can be enforced: *"pick this one and do not also use `UnrealBloomPass` from
    // `three/examples`; they are two different composer stacks and do not compose"*. Interleaving
    // them produces a black frame with no error anywhere, which is exactly the class of mistake that
    // is cheap to prevent and expensive to diagnose. Narrowed at M5a from *"never `three/examples`"*
    // to the folder that actually clashes: `GLTFLoader` is in the same tree and is the supported way
    // to read a GLB.
    const offenders: string[] = [];
    const sources: string[] = [];
    walkSource(join(PACKAGE_ROOT, 'src'), sources);
    for (const path of sources) {
      const text = readFileSync(path, 'utf8');
      if (/from\s+'three\/examples\/jsm\/postprocessing/.test(text)) offenders.push(path);
      if (/import\(\s*'three\/examples\/jsm\/postprocessing/.test(text)) offenders.push(path);
    }
    assert.deepEqual(offenders, [], `three/examples postprocessing beside pmndrs':\n${offenders.join('\n')}`);
  });

  it('never reaches a model through a bundler import', () => {
    // §5's delivery rule: *"stable runtime-fetched URLs, **not** Vite bundler imports"*. A
    // `import tree from './pine.glb?url'` would work today and would put a hashed filename in the
    // bundle that the streamer could not construct.
    const sources: string[] = [];
    walkSource(join(PACKAGE_ROOT, 'src'), sources);
    const offenders = sources.filter((path) => /from\s+'[^']*\.(glb|gltf|ktx2|png)'/.test(readFileSync(path, 'utf8')));
    assert.deepEqual(offenders, []);
  });
});

describe('the baked tree set', () => {
  if (!existsSync(TREES_DIR)) {
    it('skips: the trees have not been baked', (t) => {
      t.skip(
        `no baked trees at ${TREES_DIR} — run ` +
          `\`node --disable-warning=ExperimentalWarning packages/worldgen/src/treegen.ts\``,
      );
    });
    return;
  }

  const manifest = JSON.parse(readFileSync(join(TREES_DIR, 'manifest.json'), 'utf8')) as TreeManifest;

  it('is the version this client reads', () => {
    assert.equal(manifest.version, TREE_MANIFEST_VERSION);
    assert.ok(manifest.generator.includes('ez-tree'), 'the manifest does not say what made it');
  });

  it('lists exactly the baked variants prototypes.ts sized the pool for', () => {
    // The bounded-pool contract's second half. See this file's header, and `prototypes.ts`'s.
    //
    // The comparison is against `variantsFrom('baked')` rather than against the whole list, because
    // the list is closed and its *sources* are not: M5b's Quaternius kit trees join `TREE_VARIANTS`
    // and will never appear in the treegen manifest. Holding the baked subset exactly is the strong
    // assertion; holding the whole list would be the wrong one the day the kit lands.
    assert.deepEqual(
      manifest.trees.map((tree) => tree.id).sort(),
      [...variantsFrom('baked')].sort(),
      'the baker and the material pool disagree about which trees exist',
    );
    assert.equal(variantsFrom('baked').length + variantsFrom('kit').length, TREE_VARIANTS.length);
    for (const tree of manifest.trees) {
      assert.equal(tree.lods.length, TREE_LODS.length, `${tree.id} has ${tree.lods.length} LODs`);
      assert.deepEqual(
        tree.lods.map((lod) => lod.lod),
        [...TREE_LODS],
      );
      // Ascending, and the first takes over at zero metres or nothing would ever draw LOD0.
      assert.equal(tree.lods[0]!.distance, 0, `${tree.id} LOD0 does not start at the camera`);
      for (let i = 1; i < tree.lods.length; i++) {
        assert.ok(tree.lods[i]!.distance > tree.lods[i - 1]!.distance, `${tree.id} LOD distances`);
        // Each level really is cheaper. A "LOD" that is not is a second copy of the same tree.
        assert.ok(tree.lods[i]!.triangles < tree.lods[i - 1]!.triangles, `${tree.id} LOD${i} is not simpler`);
      }
      // The shape constants the foliage shader bends its normals with must be real numbers off a real
      // mesh — a cone slope of zero is a flat disc and would light the canopy as one blob, which is
      // §5's trap 2 arriving through the data instead of through the code.
      assert.ok(tree.height > 1 && tree.height < 30, `${tree.id} is ${tree.height} m tall`);
      assert.ok(tree.radius > 0.3, `${tree.id} has no crown`);
      assert.ok(tree.coneSlope > 0.5, `${tree.id} cone slope ${tree.coneSlope}`);
      assert.ok(tree.tiers >= 1 && tree.tiers <= 16, `${tree.id} tiers ${tree.tiers}`);
      assert.ok(tree.canopy.top > tree.canopy.base, `${tree.id} canopy band is inverted`);
    }
  });

  it('has every GLB it lists, at the byte size it recorded, inside the budget', () => {
    let total = 0;
    let triangles = 0;
    const listed = new Set<string>();
    for (const tree of manifest.trees) {
      for (const lod of tree.lods) {
        // The path is the runtime URL, relative to the served root — never an absolute disk path and
        // never a bundler specifier.
        assert.ok(lod.path.startsWith('models/trees/'), `${lod.path} is not a served path`);
        assert.ok(!lod.path.includes('..'), `${lod.path} escapes the served root`);
        const file = lod.path.slice('models/trees/'.length);
        listed.add(file);
        const onDisk = join(TREES_DIR, file);
        assert.ok(existsSync(onDisk), `${lod.path} is listed and missing`);
        assert.equal(statSync(onDisk).size, lod.bytes, `${lod.path} is not the size the manifest claims`);
        assert.ok(lod.bytes < TREE_FILE_BUDGET, `${lod.path} is ${lod.bytes} B, over the per-file budget`);
        total += lod.bytes;
        triangles += lod.triangles;
      }
    }
    // Nothing on disk that the manifest does not know about: a renamed variant's stale GLB would
    // otherwise ship for ever. `treegen` clears the directory, and this is what proves it did.
    const extra = readdirSync(TREES_DIR).filter(
      (entry) => entry !== 'manifest.json' && entry !== 'ATTRIBUTION.md' && !listed.has(entry),
    );
    assert.deepEqual(extra, [], `unlisted files in the tree directory:\n${extra.join('\n')}`);

    console.log(
      `[M5a trees] ${manifest.trees.length} variants x ${TREE_LODS.length} LODs x ${TREE_PARTS.length} meshes: ` +
        `${listed.size} GLBs, ${triangles} triangles, ${total} B (${(total / 1024).toFixed(1)} KiB) ` +
        `of a ${(TREE_SET_BUDGET / 1024 / 1024).toFixed(0)} MiB budget`,
    );
    assert.ok(total < TREE_SET_BUDGET, `the tree set is ${total} B, over budget`);
  });

  it('holds the two meshes, the card attribute and the origin the renderer expects', async () => {
    /*
     * The bake-to-client contract, closed. Everything above checks the *manifest*; this parses a real
     * GLB with the real loader and asserts the four things `world3d.ts` and `foliage.ts` assume
     * without ever checking:
     *
     * - two meshes named `trunk` and `canopy`, because the pool draws them with two materials;
     * - `uv1` on the canopy, because `trees.ts` renames it to `aCard` and the bent normals and the
     *   card jitter both read it — a canopy without it lights every card in the same tier;
     * - the trunk's foot at `y = 0`, because `scatter.ts` places a tree by its foot and a model
     *   centred on its bounding box would sink half a tree into the ground;
     * - `uv1` constant across a card's four vertices, which is the whole reason it is baked per
     *   centroid rather than derived per vertex.
     *
     * `parse` rather than `loadAsync`: there is no server here, and the bytes are the same bytes.
     */
    const { GLTFLoader } = await import('three/examples/jsm/loaders/GLTFLoader.js');
    const tree = manifest.trees[0]!;
    const file = join(TREES_DIR, tree.lods[0]!.path.slice('models/trees/'.length));
    const bytes = readFileSync(file);
    const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;

    const meshes = await new Promise<Map<string, { verts: number; attrs: string[]; minY: number; card?: Float32Array }>>(
      (resolve, reject) => {
        new GLTFLoader().parse(
          buffer,
          '',
          (gltf) => {
            const found = new Map<string, { verts: number; attrs: string[]; minY: number; card?: Float32Array }>();
            gltf.scene.traverse((node) => {
              const mesh = node as { isMesh?: boolean; name: string; geometry?: never };
              if (!mesh.isMesh) return;
              const geometry = (node as unknown as { geometry: import('three').BufferGeometry }).geometry;
              geometry.computeBoundingBox();
              const uv1 = geometry.getAttribute('uv1');
              found.set(mesh.name, {
                verts: geometry.getAttribute('position').count,
                attrs: Object.keys(geometry.attributes),
                minY: geometry.boundingBox!.min.y,
                ...(uv1 ? { card: uv1.array as Float32Array } : {}),
              });
            });
            resolve(found);
          },
          reject,
        );
      },
    );

    for (const part of TREE_PARTS) assert.ok(meshes.has(part), `${tree.id} has no ${part} mesh`);
    const trunk = meshes.get('trunk')!;
    assert.ok(Math.abs(trunk.minY) < 1e-4, `the trunk's foot is at y=${trunk.minY}, not at the origin`);
    const canopy = meshes.get('canopy')!;
    assert.ok(canopy.attrs.includes('uv1'), 'the canopy carries no card attribute');
    assert.ok(canopy.card, 'no uv1 array');
    // The first card's four vertices agree, which is what "baked per centroid" means and what keeps a
    // lighting seam out of the middle of a needle spray.
    const card = canopy.card!;
    for (let i = 1; i < 4; i++) {
      assert.equal(card[i * 2], card[0], `vertex ${i} of the first card has a different hash`);
      assert.equal(card[i * 2 + 1], card[1], `vertex ${i} of the first card has a different tier`);
    }
    assert.ok(card[1]! >= 0 && card[1]! <= 1, 'the tier coordinate is not normalised');
  });

  it('carries the attribution the licences require', () => {
    // `CLAUDE.md`: *"attribution is mandatory, so every asset folder keeps its upstream `LICENSE` and
    // `AUTHORS` file"*. This folder's honest answer is unusual and the note has to say so — the
    // geometry is generated, no upstream texture is redistributed, and MIT still asks for the notice.
    const note = readFileSync(join(TREES_DIR, 'ATTRIBUTION.md'), 'utf8');
    assert.ok(note.includes('MIT'), 'the attribution names no licence');
    assert.ok(note.includes('ez-tree'), 'the attribution does not credit the generator');
    assert.ok(note.includes('treegen.ts'), 'the attribution does not say how to re-create the set');
    for (const tree of manifest.trees) {
      assert.ok(note.includes(tree.id), `${tree.id} is not in the attribution note`);
    }
  });
});
