/**
 * Loading a zone's population file.
 *
 * The counterpart to `loadZone` in `world.ts`, and it takes the same view of a missing file: **a zone with
 * no population file is simply empty**. That is the ordinary case, not an error — only 49 of 327 zones
 * match a Duris `.wld` at all, and of those several are rooms with nobody in them. Refusing to start over
 * an absent file would make the zone list impossible to edit.
 *
 * A *malformed* file is different and does throw, for the reason `loadWorldConfig` does: it is generated,
 * so a bad one means the pipeline is broken, and a silently half-loaded zone is much harder to notice than
 * a refusal to boot.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import type { MobTemplate, ZoneId, ZoneSpawns } from '@mygame/shared';

import { WORLD_DIR } from './world.ts';

/** Where `npm run worldgen` writes population files. */
export const SPAWNS_DIR = join(WORLD_DIR, 'spawns');

export function spawnPath(zone: ZoneId): string {
  return join(SPAWNS_DIR, `${zone}.json`);
}

/**
 * Reads one zone's population, or nothing if it has none.
 *
 * Shape-checked rather than trusted. It is generated data, but it is generated by a *different package*
 * and read by this one, and the failure a check catches — a `resets` array of the wrong shape — would
 * otherwise surface as a mob spawning in room `undefined` several minutes into a session.
 */
export function loadZoneSpawns(zone: ZoneId): ZoneSpawns | undefined {
  const path = spawnPath(zone);
  if (!existsSync(path)) return undefined;

  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(path, 'utf8'));
  } catch (cause) {
    throw new Error(`${path} is not valid JSON. Re-run \`npm run worldgen\`.`, { cause });
  }
  if (typeof parsed !== 'object' || parsed === null) {
    throw new Error(`${path} is malformed: expected a JSON object.`);
  }
  const raw = parsed as Record<string, unknown>;
  if (!Array.isArray(raw['templates']) || !Array.isArray(raw['resets'])) {
    throw new Error(`${path} is malformed: "templates" and "resets" must both be arrays.`);
  }
  return parsed as ZoneSpawns;
}

/**
 * Every template across every loaded zone, by vnum.
 *
 * One flat index rather than one per zone, because **instance limits are world-wide**: the reset executor
 * asks "how many of vnum 97018 exist anywhere", so it needs to resolve a vnum without knowing which zone
 * asked. Two zones sharing a vnum is not a conflict either — three of our zones matched the same
 * `undermountain.wld`, so they share templates by construction, and the last writer wins on identical
 * data.
 */
export function indexTemplates(spawns: Iterable<ZoneSpawns>): Map<number, MobTemplate> {
  const out = new Map<number, MobTemplate>();
  for (const zone of spawns) {
    for (const template of zone.templates) out.set(template.vnum, template);
  }
  return out;
}
