/**
 * Loading a zone's population file.
 *
 * The counterpart to `loadZone` in `world.ts`, and it takes the same view of a missing file: **a zone with
 * no population file is simply empty**. That is the ordinary case, not an error — only 49 of 327 zones
 * match a Duris `.wld` at all, and of those several are rooms with nobody in them. Refusing to start over
 * an absent file would make the zone list impossible to edit.
 *
 * A *malformed* file is different and does throw, for the reason `loadWorldConfig` does: it is generated,
 * so a bad one means the pipeline is broken, and a silently half-loaded zone is much harder to notice than
 * a refusal to boot.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import type { ItemTemplate, MobTemplate, ZoneId, ZoneSpawns } from '@mygame/shared';

import { WORLD_DIR } from './world.ts';

/** Where `npm run worldgen` writes population files. */
export const SPAWNS_DIR = join(WORLD_DIR, 'spawns');

export function spawnPath(zone: ZoneId): string {
  return join(SPAWNS_DIR, `${zone}.json`);
}

/**
 * Reads one zone's population, or nothing if it has none.
 *
 * Shape-checked rather than trusted. It is generated data, but it is generated by a *different package*
 * and read by this one, and the failure a check catches — a `resets` array of the wrong shape — would
 * otherwise surface as a mob spawning in room `undefined` several minutes into a session.
 */
export function loadZoneSpawns(zone: ZoneId): ZoneSpawns | undefined {
  const path = spawnPath(zone);
  if (!existsSync(path)) return undefined;

  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(path, 'utf8'));
  } catch (cause) {
    throw new Error(`${path} is not valid JSON. Re-run \`npm run worldgen\`.`, { cause });
  }
  if (typeof parsed !== 'object' || parsed === null) {
    throw new Error(`${path} is malformed: expected a JSON object.`);
  }
  const raw = parsed as Record<string, unknown>;
  if (!Array.isArray(raw['templates']) || !Array.isArray(raw['resets'])) {
    throw new Error(`${path} is malformed: "templates" and "resets" must both be arrays.`);
  }
  return parsed as ZoneSpawns;
}

/**
 * How long an unharvested zone waits between repops, in zone ticks.
 *
 * **Measured, not chosen**: `15`/`25` is the modal lifespan across the 49 harvested zones — ten of them
 * use exactly this pair, more than any other. A zone whose population is entirely authored has no `.zon`
 * of its own to state a lifespan, so it borrows the one the world states most often rather than a number
 * somebody liked. At `ZONE_TICK_MS` that is a repop every 19–31 minutes.
 */
export const AUTHORED_LIFESPAN_MIN = 15;
export const AUTHORED_LIFESPAN_MAX = 25;

/**
 * A zone that is populated **without a harvest** — an empty table with a clock that runs.
 *
 * `loadZoneSpawns` returning `undefined` used to mean *this zone is empty*, and for the 278 zones no
 * Duris file matched that is still true. But it also silently meant *this zone can never be populated*,
 * because a zone only reaches `zoneClocks` by way of a `ZoneSpawns`, and authored placements are merged
 * into a zone's reset table rather than being a table of their own. A zone with no harvested file got no
 * entry, so a placement into it never spawned — and it failed more quietly than "homeless" suggests.
 * The boot's homeless count asks whether a placement's *room* resolves to a zone, which it does, so
 * such a placement was counted as homed and then had no table to be merged into. Nothing said anything.
 *
 * The shell separates the two questions. **Whether a zone has a harvest** and **whether a zone is
 * populated** are different facts: the first is about `data/world/spawns/`, the second is `world.config.json`'s
 * `populate` list, and this is what lets the second stand on its own. A zone listed to populate gets a
 * clock either way; what fills it is the harvest, the authored placements, or both.
 *
 * That generality is the point rather than a side effect. The two Faerie Courts are the first zones to
 * need it — neither has a Duris `.wld` behind it, so neither was ever harvested — but `docs/DESIGN-city.md`'s
 * Phase 22 city zones are authored from nothing at all and will have no harvested file either. The rule
 * this encodes is *a zone can be populated without a harvest*, not *the faerie zones are special*.
 *
 * `templates` is empty because a template is world-wide (see {@link indexTemplates}) — an authored
 * placement names a vnum that some other zone's harvest or `mobs-authored.json` already defines, so there
 * is nothing for this zone to contribute. `resets` is empty for the same reason: everything that fills
 * this zone arrives later, appended by `placementResets`.
 */
export function emptyZoneSpawns(zone: ZoneId): ZoneSpawns {
  return {
    zone,
    // Named rather than blank so the boot log and a bad-row trace can both say where this came from,
    // and so `authored` never collides with a `.wld` filename.
    source: 'authored',
    lifespanMin: AUTHORED_LIFESPAN_MIN,
    lifespanMax: AUTHORED_LIFESPAN_MAX,
    templates: [],
    resets: [],
  };
}

/**
 * Every template across every loaded zone, by vnum.
 *
 * One flat index rather than one per zone, because **instance limits are world-wide**: the reset executor
 * asks "how many of vnum 97018 exist anywhere", so it needs to resolve a vnum without knowing which zone
 * asked. Two zones sharing a vnum is not a conflict either — three of our zones matched the same
 * `undermountain.wld`, so they share templates by construction, and the last writer wins on identical
 * data.
 */
export function indexTemplates(spawns: Iterable<ZoneSpawns>): Map<number, MobTemplate> {
  const out = new Map<number, MobTemplate>();
  for (const zone of spawns) {
    for (const template of zone.templates) out.set(template.vnum, template);
  }
  return out;
}

/* -------------------------------------------------------------------------- */
/* The item catalogue                                                          */
/* -------------------------------------------------------------------------- */

/** Where `npm run worldgen` writes the item catalogue. One file for the whole world — see 15c. */
export const ITEMS_FILE = join(WORLD_DIR, 'items.json');

/**
 * Every item type in the world, by vnum.
 *
 * **One flat map, loaded once at boot**, for the same reason {@link indexTemplates} is flat: a `G`
 * command in IceCrag can name an object whose definition lives in a file belonging to somewhere else
 * entirely, because `real_object` in the source is a world-wide lookup. There is no per-zone answer to
 * "what is object 91000".
 *
 * A missing file is **empty rather than fatal**, exactly as an absent population file is. The catalogue
 * is derived from `data/zones-source/`, which is git-ignored and may simply not be there — and a world
 * whose mobs carry nothing is the world we shipped through 15b. A *malformed* one throws, because that
 * means the pipeline is broken.
 */
export function loadItemCatalogue(file = ITEMS_FILE): Map<number, ItemTemplate> {
  const out = new Map<number, ItemTemplate>();
  if (!existsSync(file)) return out;

  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(file, 'utf8'));
  } catch (cause) {
    throw new Error(`${file} is not valid JSON. Re-run \`npm run worldgen\`.`, { cause });
  }
  if (!Array.isArray(parsed)) {
    throw new Error(`${file} is malformed: expected an array of item templates.`);
  }
  for (const entry of parsed) {
    const template = entry as Partial<ItemTemplate>;
    // Shape-checked on the three fields everything downstream assumes. A row missing one of them would
    // otherwise surface as an item with no name lying on a floor somewhere.
    if (typeof template.vnum !== 'number' || typeof template.name !== 'string' || typeof template.size !== 'number') {
      continue;
    }
    out.set(template.vnum, template as ItemTemplate);
  }
  return out;
}
