/**
 * Loading a zone's population file.
 *
 * The counterpart to `loadZone` in `world.ts`, and it takes the same view of a missing file: **a zone with
 * no population file is simply empty**. That is the ordinary case, not an error — only 49 of 327 zones
 * match a Duris `.wld` at all, and of those several are rooms with nobody in them. Refusing to start over
 * an absent file would make the zone list impossible to edit.
 *
 * A *malformed* file is different and does throw, for the reason `loadWorldConfig` does: it is generated,
 * so a bad one means the pipeline is broken, and a silently half-loaded zone is much harder to notice than
 * a refusal to boot.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import type { ItemTemplate, MobTemplate, ZoneId, ZoneSpawns } from '@mygame/shared';

import { WORLD_DIR } from './world.ts';

/** Where `npm run worldgen` writes population files. */
export const SPAWNS_DIR = join(WORLD_DIR, 'spawns');

export function spawnPath(zone: ZoneId): string {
  return join(SPAWNS_DIR, `${zone}.json`);
}

/**
 * Reads one zone's population, or nothing if it has none.
 *
 * Shape-checked rather than trusted. It is generated data, but it is generated by a *different package*
 * and read by this one, and the failure a check catches — a `resets` array of the wrong shape — would
 * otherwise surface as a mob spawning in room `undefined` several minutes into a session.
 */
export function loadZoneSpawns(zone: ZoneId): ZoneSpawns | undefined {
  const path = spawnPath(zone);
  if (!existsSync(path)) return undefined;

  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(path, 'utf8'));
  } catch (cause) {
    throw new Error(`${path} is not valid JSON. Re-run \`npm run worldgen\`.`, { cause });
  }
  if (typeof parsed !== 'object' || parsed === null) {
    throw new Error(`${path} is malformed: expected a JSON object.`);
  }
  const raw = parsed as Record<string, unknown>;
  if (!Array.isArray(raw['templates']) || !Array.isArray(raw['resets'])) {
    throw new Error(`${path} is malformed: "templates" and "resets" must both be arrays.`);
  }
  return parsed as ZoneSpawns;
}

/**
 * Every template across every loaded zone, by vnum.
 *
 * One flat index rather than one per zone, because **instance limits are world-wide**: the reset executor
 * asks "how many of vnum 97018 exist anywhere", so it needs to resolve a vnum without knowing which zone
 * asked. Two zones sharing a vnum is not a conflict either — three of our zones matched the same
 * `undermountain.wld`, so they share templates by construction, and the last writer wins on identical
 * data.
 */
export function indexTemplates(spawns: Iterable<ZoneSpawns>): Map<number, MobTemplate> {
  const out = new Map<number, MobTemplate>();
  for (const zone of spawns) {
    for (const template of zone.templates) out.set(template.vnum, template);
  }
  return out;
}

/* -------------------------------------------------------------------------- */
/* The item catalogue                                                          */
/* -------------------------------------------------------------------------- */

/** Where `npm run worldgen` writes the item catalogue. One file for the whole world — see 15c. */
export const ITEMS_FILE = join(WORLD_DIR, 'items.json');

/**
 * Every item type in the world, by vnum.
 *
 * **One flat map, loaded once at boot**, for the same reason {@link indexTemplates} is flat: a `G`
 * command in IceCrag can name an object whose definition lives in a file belonging to somewhere else
 * entirely, because `real_object` in the source is a world-wide lookup. There is no per-zone answer to
 * "what is object 91000".
 *
 * A missing file is **empty rather than fatal**, exactly as an absent population file is. The catalogue
 * is derived from `data/zones-source/`, which is git-ignored and may simply not be there — and a world
 * whose mobs carry nothing is the world we shipped through 15b. A *malformed* one throws, because that
 * means the pipeline is broken.
 */
export function loadItemCatalogue(file = ITEMS_FILE): Map<number, ItemTemplate> {
  const out = new Map<number, ItemTemplate>();
  if (!existsSync(file)) return out;

  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(file, 'utf8'));
  } catch (cause) {
    throw new Error(`${file} is not valid JSON. Re-run \`npm run worldgen\`.`, { cause });
  }
  if (!Array.isArray(parsed)) {
    throw new Error(`${file} is malformed: expected an array of item templates.`);
  }
  for (const entry of parsed) {
    const template = entry as Partial<ItemTemplate>;
    // Shape-checked on the three fields everything downstream assumes. A row missing one of them would
    // otherwise surface as an item with no name lying on a floor somewhere.
    if (typeof template.vnum !== 'number' || typeof template.name !== 'string' || typeof template.size !== 'number') {
      continue;
    }
    out.set(template.vnum, template as ItemTemplate);
  }
  return out;
}
