/**
 * A harvested zone's **name**, re-authored — the one field no overlay could reach.
 *
 * Every other piece of a harvested zone has had an overlay since Phase 15c: rooms have
 * `rooms.json` (name, prose, sector, flags), mobs have `mobs.json`, items have `items.json`. A
 * *zone's* name had none, because nothing had ever needed one: `zones-authored.json` names zones
 * we created, and the harvest's own names came off the zMUD map and were treated as fact.
 *
 * The Tordraken rewrite is what needed it (owner, 2026-08-09: *"I would also like to rename Icecrag
 * Castle to Tordraken Castle… so it will need a rewrite"*). The zone name is what the client prints
 * on the place card and what the admin panel lists, so a castle re-themed room by room while its
 * zone still announced itself as IceCrag would be a rename that stopped at the door.
 *
 * Deliberately thin, and deliberately *not* merged into `rooms.json`: that file is keyed by room id
 * and a zone id in it would be a second id space sharing one map. Composed at boot exactly as room
 * overrides are — see `GameWorld.load` — so `npm run worldgen` can rebuild the harvest underneath a
 * rename for ever, which is the property every overlay in this project exists to have.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { Zone, ZoneId } from '@mygame/shared';

// The path is computed here rather than imported from `world.ts` — `world.ts` composes *this*
// module at load, and an import back would be a cycle. `settings.ts` does the same for the same
// reason, and the duplication is three lines against a knot.
const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');

/** Beside its siblings, and for their reason: nothing regenerates it. */
export const ZONE_OVERRIDES_FILE = join(REPO_ROOT, 'data', 'world', 'overrides', 'zones.json');

/** How long a zone's name may be — `zone-authoring.ts`'s own bound, shared by hand rather than imported to keep this module standalone. */
export const ZONE_NAME_LIMIT = 60;

export interface ZoneOverride {
  readonly name?: string;
  /**
   * Render this zone as continuous terrain — V8c, and the design's own words: *"a per-zone
   * rendering choice, not a fork of the pipeline."*
   *
   * An authored zone declares `seamless` in its own file because we write that file. A **harvested**
   * one cannot: `data/world/zones/` is regenerated by `npm run worldgen` and anything written there
   * is lost on the next build. So the choice lives here, beside the rename, and is composed at boot
   * the same way.
   *
   * **It is a choice and not a default, for a mechanical reason as well as a taste one.** `ROOM_GAP`
   * is tuned against `DEFAULT_LIGHT_RADIUS` — at a gap of 2 the next room sits 3 tiles away, which
   * is invisible at the starting light radius and visible once you find a torch, and that
   * relationship is what makes a light source feel like an upgrade. A seam of 1 puts the next room
   * within reach of any light at all. Outdoors in daylight that is exactly right; in a dark dungeon
   * it would quietly delete the mechanic. Hence: fields and forests yes, caves and castles no.
   */
  readonly seamless?: boolean;
  readonly at?: string;
  readonly by?: string;
}

export type ZoneOverrideStore = Map<ZoneId, ZoneOverride>;

/**
 * Reads the overlay, tolerating anything — every sibling loader's posture. A malformed row is
 * dropped rather than thrown on: a hand-edited file must not be able to stop the server booting,
 * and a zone that keeps its harvested name is a cosmetic loss, not a broken world.
 */
export function loadZoneOverrides(file = ZONE_OVERRIDES_FILE): ZoneOverrideStore {
  const store: ZoneOverrideStore = new Map();
  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(file, 'utf8'));
  } catch {
    return store;
  }
  if (typeof raw !== 'object' || raw === null) return store;
  for (const [key, value] of Object.entries(raw as Record<string, unknown>)) {
    const id = Number(key);
    if (!Number.isInteger(id)) continue;
    if (typeof value !== 'object' || value === null) continue;
    const row = value as Record<string, unknown>;
    const name = typeof row.name === 'string' ? row.name.trim() : '';
    // A row may carry either field or both — a rename with no rendering change, or a rendering
    // change with no rename. Only a row carrying *neither* is nothing, and is dropped.
    const named = name.length > 0 && name.length <= ZONE_NAME_LIMIT;
    const seamless = row.seamless === true;
    if (!named && !seamless) continue;
    store.set(id as ZoneId, {
      ...(named ? { name } : {}),
      ...(seamless ? { seamless: true } : {}),
      ...(typeof row.at === 'string' ? { at: row.at } : {}),
      ...(typeof row.by === 'string' ? { by: row.by } : {}),
    });
  }
  return store;
}

export function saveZoneOverrides(store: ZoneOverrideStore, file = ZONE_OVERRIDES_FILE): void {
  mkdirSync(dirname(file), { recursive: true });
  const out: Record<string, ZoneOverride> = {};
  for (const id of [...store.keys()].sort((a, b) => a - b)) out[String(id)] = store.get(id)!;
  writeFileSync(file, `${JSON.stringify(out, null, 2)}\n`, 'utf8');
}

/**
 * Applies a rename to a zone in place, returning whether it changed anything.
 *
 * In place because `GameWorld` already mutates the zone objects it loads (see `relaxLocks`), and a
 * rebuilt record here would be a second copy for every consumer to disagree over.
 */
export function applyZoneOverride(
  zone: { name: string; id: ZoneId; seamless?: boolean },
  store: ZoneOverrideStore,
): boolean {
  const override = store.get(zone.id);
  if (!override) return false;
  let changed = false;
  if (override.name && override.name !== zone.name) {
    zone.name = override.name;
    changed = true;
  }
  if (override.seamless === true && zone.seamless !== true) {
    zone.seamless = true;
    changed = true;
  }
  return changed;
}

/** Convenience for callers holding a whole `Zone`. Returns how many zones the overlay touched. */
export function renameZones(zones: readonly Zone[], store: ZoneOverrideStore): number {
  let changed = 0;
  for (const zone of zones) {
    if (applyZoneOverride(zone as { name: string; id: ZoneId; seamless?: boolean }, store)) changed += 1;
  }
  return changed;
}
