/**
 * **Generated by `npm run creaturegen` — do not edit.**
 *
 * What a creature is made of: bodies, head shapes and tails indexed from `assets/ulpc` and staged
 * into `packages/client/public/lpc/<id>.png`, so the id *is* the texture key. Every entry resolved
 * to a real 576x256 walk sheet, which is the only geometry the renderer can draw.
 *
 * Separate from `lpc-art.ts` on purpose — that is what a character *wears*, this is what one *is*,
 * and an item picker must never be able to offer a wolf's head as a hat.
 *
 * Attribution is `ATTRIBUTION-generated.md`, beside the staged files. CC-BY-SA 3.0 / GPL / OGA-BY,
 * and attribution is mandatory — see `CLAUDE.md`.
 */

/** One indexed creature layer. */
export interface CreatureLayer {
  readonly id: string;
  readonly part: 'body' | 'head' | 'tail';
  /** The pack's own word: `wolf`, `muscular`, `lizard`. */
  readonly shape: string;
  /** The pack's variant beneath it: `male`, `adult`, `child`. */
  readonly variant: string;
  /** Action poses staged beside the walk cycle. */
  readonly actions: readonly string[];
}

export const CREATURE_LAYERS: readonly CreatureLayer[] = [
  { id: "body-child", part: "body", shape: "child", variant: "default", actions: ["slash"] },
  { id: "body-female", part: "body", shape: "female", variant: "default", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "body-male", part: "body", shape: "male", variant: "default", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "body-muscular", part: "body", shape: "muscular", variant: "default", actions: ["slash","spellcast","thrust"] },
  { id: "body-pregnant", part: "body", shape: "pregnant", variant: "default", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "body-skeleton", part: "body", shape: "skeleton", variant: "default", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "body-teen", part: "body", shape: "teen", variant: "default", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-alien-adult", part: "head", shape: "alien", variant: "adult", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-boarman-adult", part: "head", shape: "boarman", variant: "adult", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-boarman-child", part: "head", shape: "boarman", variant: "child", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-frankenstein-adult", part: "head", shape: "frankenstein", variant: "adult", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-goblin-adult", part: "head", shape: "goblin", variant: "adult", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-goblin-child", part: "head", shape: "goblin", variant: "child", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-human-child", part: "head", shape: "human", variant: "child", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-human-elderly_small", part: "head", shape: "human", variant: "elderly_small", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-human-female", part: "head", shape: "human", variant: "female", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-human-female_elderly", part: "head", shape: "human", variant: "female_elderly", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-human-female_small", part: "head", shape: "human", variant: "female_small", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-human-male", part: "head", shape: "human", variant: "male", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-human-male_elderly", part: "head", shape: "human", variant: "male_elderly", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-human-male_gaunt", part: "head", shape: "human", variant: "male_gaunt", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-human-male_plump", part: "head", shape: "human", variant: "male_plump", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-human-male_small", part: "head", shape: "human", variant: "male_small", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-jack-adult", part: "head", shape: "jack", variant: "adult", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-lizard-child", part: "head", shape: "lizard", variant: "child", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-lizard-female", part: "head", shape: "lizard", variant: "female", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-lizard-male", part: "head", shape: "lizard", variant: "male", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-minotaur-child", part: "head", shape: "minotaur", variant: "child", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-minotaur-female", part: "head", shape: "minotaur", variant: "female", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-minotaur-male", part: "head", shape: "minotaur", variant: "male", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-mouse-adult", part: "head", shape: "mouse", variant: "adult", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-mouse-child", part: "head", shape: "mouse", variant: "child", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-orc-child", part: "head", shape: "orc", variant: "child", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-orc-female", part: "head", shape: "orc", variant: "female", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-orc-male", part: "head", shape: "orc", variant: "male", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-pig-adult", part: "head", shape: "pig", variant: "adult", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-pig-child", part: "head", shape: "pig", variant: "child", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-rabbit-adult", part: "head", shape: "rabbit", variant: "adult", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-rabbit-child", part: "head", shape: "rabbit", variant: "child", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-rat-adult", part: "head", shape: "rat", variant: "adult", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-rat-child", part: "head", shape: "rat", variant: "child", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-sheep-adult", part: "head", shape: "sheep", variant: "adult", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-sheep-child", part: "head", shape: "sheep", variant: "child", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-skeleton-adult", part: "head", shape: "skeleton", variant: "adult", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-troll-adult", part: "head", shape: "troll", variant: "adult", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-troll-child", part: "head", shape: "troll", variant: "child", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-vampire-adult", part: "head", shape: "vampire", variant: "adult", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-wartotaur-adult", part: "head", shape: "wartotaur", variant: "adult", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-wolf-child", part: "head", shape: "wolf", variant: "child", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-wolf-female", part: "head", shape: "wolf", variant: "female", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-wolf-male", part: "head", shape: "wolf", variant: "male", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "head-shape-zombie-adult", part: "head", shape: "zombie", variant: "adult", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "tail-lizard-adult-bg", part: "tail", shape: "lizard", variant: "adult\\bg", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "tail-lizard-adult-fg", part: "tail", shape: "lizard", variant: "adult\\fg", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "tail-lizard-child-bg", part: "tail", shape: "lizard", variant: "child\\bg", actions: ["shoot","slash","spellcast","thrust"] },
  { id: "tail-lizard-child-fg", part: "tail", shape: "lizard", variant: "child\\fg", actions: ["shoot","slash","spellcast","thrust"] },
];

export const CREATURE_LAYER_BY_ID: ReadonlyMap<string, CreatureLayer> = new Map(
  CREATURE_LAYERS.map((l) => [l.id, l]),
);

/** Every distinct head shape the pack gave us — the vocabulary a matcher may choose from. */
export const HEAD_SHAPES: readonly string[] = [
  ...new Set(CREATURE_LAYERS.filter((l) => l.part === 'head').map((l) => l.shape)),
].sort();

/** Every distinct body. */
export const BODY_SHAPES: readonly string[] = [
  ...new Set(CREATURE_LAYERS.filter((l) => l.part === 'body').map((l) => l.shape)),
].sort();
